- name: Demo on Loops
  hosts: localhost
  connection: local
  vars:
    fruits:
      - orange
      - apple
  tasks:
    - name: Print fruits
      ansible.builtin.debug:
        msg: Fruit name - "{{ items }}"
      loop: "{{ fruits }}"

    - name: Print fruit local variables
      ansible.builtin.debug:
        msg: Fruit name - "{{ items }}"
      loop:
        - banana
        - kiwi